/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ancientGate.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ancientGate.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.imagetostl_mesh0.geometry} material={materials.mat0} />
    </group>
  )
}

useGLTF.preload('/ancientGate.glb')
