/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ancient_arch_portal.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Ancient_arch_portal(props) {
  const { nodes, materials } = useGLTF('../../modelos/ancient_arch_portal.glb')
  materials.glass.map = props.map;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ARch001.geometry} material={materials.rock1} position={[0, 0.81, 0]} />
      <mesh geometry={nodes.portal.geometry} material={materials.glass} position={[0, 0.71, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
    </group>
  )
}

useGLTF.preload('../../modelos/ancient_arch_portal.glb')
