/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\huey_tlatoani.glb
Author: Alejandro G. Gaona (https://sketchfab.com/alejandroggaona)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/huey-tlatoani-aztec-emperor-b2c16351e59b473e8b6c67f90142d3b7
Title: Huey Tlatoani - Aztec Emperor
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Guarda(props) {
  const { nodes, materials } = useGLTF('../../modelos/huey_tlatoani.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI]}>
        <lineSegments geometry={nodes.Object_2.geometry} material={materials.HairMatAniso_mesh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.HairMatAniso_mesh} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.UV_CHECK} />
      </group>
    </group>
  )
}

useGLTF.preload('../../modelos/huey_tlatoani.glb')
