/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 .\pumpkin.glb
Author: chris munoz (https://sketchfab.com/chrismunoz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-pumpkin-4741375aac2c429fbaae01ae70179a60
Title: Low Poly Pumpkin :)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Pumpkin(props) {
    const { nodes, materials } = useGLTF('../../modelos/pumpkin.glb')
    console.log(nodes)
    console.log(materials)
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={2.3} position={[0, 0, 0]}>
                <group position={[1.19, 0.023, 0.381]} scale={0.028}>
                    <mesh geometry={nodes.Cube_0.geometry} material={materials['Material.002']} />
                    <mesh geometry={nodes.Leaf001_0.geometry} material={materials['Material.002']} position={[-87.04, -38.564, 22.653]} rotation={[0.667, 0.181, 1.614]} scale={95.253} />
                    <mesh geometry={nodes.Leaf003_0.geometry} material={materials['Material.002']} position={[-5.541, -35.703, 3.467]} rotation={[-0.157, 0.454, 2.851]} scale={85.604} />
                    <mesh geometry={nodes.Leaf005_0.geometry} material={materials['Material.002']} position={[5.404, -10.015, 1.843]} rotation={[0.24, 0.494, -1.621]} scale={46.945} />
                    <mesh geometry={nodes.Leaf006_0.geometry} material={materials['Material.002']} position={[-48.781, -45.928, 14.247]} rotation={[0.481, -0.344, -1.959]} scale={67.347} />
                    <mesh geometry={nodes.Leaf_0.geometry} material={materials['Material.002']} position={[8.816, 21.274, 7.609]} rotation={[0.462, 0.723, -0.486]} scale={75.538} />
                </group>
                <mesh geometry={nodes.Tija_0.geometry} material={materials['Material.002']} position={[0.009, 0.003, 1.608]} scale={0.261} />
                {/* <mesh geometry={nodes.Terra_0.geometry} material={materials['Material.001']} /> */}
                <mesh geometry={nodes.Pumpkin_0.geometry} material={materials['Material.002']} position={[0.013, 0, 0.782]} scale={[1, 1, 0.821]} />
                <mesh geometry={nodes.Leaf004_0.geometry} material={materials['Material.002']} position={[0.783, 1.024, 0.751]} rotation={[-0.173, 0.523, 0.725]} scale={1.46} />
                <mesh geometry={nodes.Leaf002_0.geometry} material={materials['Material.002']} position={[0.12, 1.241, 0.297]} rotation={[-0.735, 0.068, 0.985]} scale={3.072} />
            </group>
        </group>
    )
}

useGLTF.preload('../../modelos/pumpkin.glb')
